project_id = "shnawhdsgnrszjrobwwy"

[functions.analyze-code]
verify_jwt = false

[functions.mint-nft]
verify_jwt = true

[functions.analyze-profile]
verify_jwt = true

[functions.mock-interview]
verify_jwt = true

[functions.verify-certification]
verify_jwt = true